name: startup1
favicon: null
layout_spectrum: 0.06615
typography_spectrum: 0.64212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#542d13'
    - '#c1c5c8'
    - '#94989b'
    - '#a47459'
    - '#ff0000'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
