name: startup1
favicon: null
layout_spectrum: 0.00193
typography_spectrum: 0.64212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#0f0f0f'
    - '#959595'
    - '#3d3d3d'
    - '#626262'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
